import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import Header from '@/app/components/ui/Header'
import './globals.scss'
import './theme.scss'

import ThemeProvider from "@/app/components/ui/ThemeProvider";
import StoreProvider from "@/app/components/ui/StoreProvider";

const roboto = Roboto({subsets: ['latin'], weight: '400'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${roboto.className} antialiased`}>
        <StoreProvider>
            <ThemeProvider>
                <div className={"min-h-screen home-wrap"}>
                    <Header/>
                    {children}
                </div>
            </ThemeProvider>
        </StoreProvider>
        </body>
        </html>
    )
}
